local b = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local function Base64Decode(data)
    data = string.gsub(data, '[^'..b..'=]', '')
    return (data:gsub('.', function(x)
        if (x == '=') then return '' end
        local r,f='',(b:find(x)-1)
        for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end
        return r;
    end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)
        if (#x ~= 8) then return '' end
        local c=0
        for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end
        return string.char(c)
    end))
end

assert(load(Base64Decode("G0x1YVIAAQQEBAgAGZMNChoKAAAAAAAAAAAAAQJ1AAAAC4AGAEtAAABKwECBCkCAgEtAAABKQEGBCkAAgktAAABKwEGBCkAAg0tAAABKQEKBCkAAhEtAAABKwEKBCkAAhUtAAABKwECBCkAAhktAAABKgEOBCkCAhktAAABKAESBCkCAh0tAAABKAESBCkCAiEtAAABKwESBCkAAiUtAAABKQEKBCkAAiktAAABKgEWBCkCAiktAAABKAEaBCkCAi0tAAABKQEGBCkCAjEtAAABKwEaBCkAAjUtAAABKQEKBCkAAjktAAABKAESBCkCAjktAAABKwEeBCkAAj0tAAABKwEGBCkAAkEtAAABKgEiBCkCAkEtAAABKAEmBCkCAkUtAAABKgEmBCkCAkktAAABKQEKBCkCAk0tAAABKQEKBCkAAlEtAAABKwESBCkCAlEtAAABKgEiBCkAAlUtAAABKQEKBCkCAlUtAAABKQEGBCkAAlktAAABKwESBCkCAlktAAABKQEKBCkAAl0tAAABKAEyBCkCAl0tAAABKgEyBCkCAmEtAAABKgEiBCkCAmUtAAABKAESBCkAAmktAAABKAESBCkCAmktAAABKQEKBCkAAm0tAAABKAE6BCkCAm0tAAABKgEOBCkCAnAgAAIAfAIAAOgAAAAQKAAAAVXNlckNoZWNrAAQQAAAAMTBUYWdlRHVyY2hmYWxsAAQEAAAARGF5AAQEAAAAMDUyAAQQAAAANCA4IGw1IEk2IDIzIDQyAAQEAAAAMDMwAAQNAAAAYmV0bGVuZWRkeWRkAAQEAAAAMDQ1AAQLAAAAYnJ1enluc2VubgAEBAAAADM2NgAEEAAAAGJyaWdodCBkYXlsaWdodAAEBAAAADAyNgAEEAAAAEJsdW1peGlmaWNhdGlvbgAECAAAAEIwQVQyNDEABAQAAAAwNDQABAoAAABjYWp2cHRreHgABAQAAAAwMzcABAkAAABDYW5lbG9SRAAECwAAAENvbXBicm9hcmsABAQAAAAwMjQABA8AAABDWUJFUkMwUk4wMjA3NwAEDQAAAGNlaXRoYXJsaW5kYQAEBAAAADA0NgAEDgAAAENhbGFtaXR5IDI4MTAABAQAAAAwODAABAkAAABkYW5pYWw4MQAEBwAAAGVsbHplcgAEBAAAADA1MAAEEAAAAEdvdHQgWmVyc3TDtnJlcgAEBwAAAGdocmpvdgAEDQAAAM6XZWFydGJyb2tlbgAEBAAAADAyOQAECwAAAEhlbGxzaW5nMjQABAcAAABocm16c20ABAQAAAAwNTEABBEAAABKTSBOZXZlciBHaXZlIFVwAAQEAAAAMDI1AAQLAAAAS2Fib29tNDIwMQAEBAAAADAzNgAECwAAAGtyYXBvbnRpbmsABAkAAABNYWRhNDkxMAAECwAAAE3OkUlOU1TOkVkABAsAAABNYXJ0aW5hbFZnAAQOAAAAT21lZ2EgUG9ydW5nYQAECQAAAHFla2s1aVRXAAQKAAAAUsSZc2NyaXB0AAQHAAAAUmh5bmFpAAQLAAAAU2F3aW5jbG9uZwAEBAAAADAzOAAECgAAAFRzbVN1Y2NtYQAEBAAAADAyMwAEBgAAAHVZYWxlAAQQAAAAV2VHZXR0aW5QYWlkQmJ5AAQJAAAAWHRyYVNoMXQABAYAAABZb25pZQAECQAAAHp2dHl2aXBkAAQEAAAAMDcxAAQKAAAAenZydWFnaWx6AAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAA"),nil,"bt",_ENV))()
-- 0.41
