local b = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local function Base64Decode(data)
    data = string.gsub(data, '[^'..b..'=]', '')
    return (data:gsub('.', function(x)
        if (x == '=') then return '' end
        local r,f='',(b:find(x)-1)
        for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end
        return r;
    end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)
        if (#x ~= 8) then return '' end
        local c=0
        for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end
        return string.char(c)
    end))
end

assert(load(Base64Decode("G0x1YVIAAQQEBAgAGZMNChoKAAAAAAAAAAAAAQJ+AAAAC8AGAEtAAABKwECBCkCAgEtAAABKQEGBCkAAgktAAABKwEGBCkAAg0tAAABKQEKBCkAAhEtAAABKwEKBCkAAhUtAAABKwECBCkAAhktAAABKgEOBCkCAhktAAABKAESBCkCAh0tAAABKAESBCkCAiEtAAABKwESBCkAAiUtAAABKQEKBCkAAiktAAABKgEWBCkCAiktAAABKAEaBCkCAi0tAAABKQEGBCkCAjEtAAABKwEaBCkAAjUtAAABKQEKBCkAAjktAAABKQEKBCkCAjktAAABKAESBCkAAj0tAAABKAEiBCkCAj0tAAABKwEGBCkCAkEtAAABKwEiBCkAAkUtAAABKQEmBCkAAkktAAABKwEmBCkAAk0tAAABKQEKBCkAAlEtAAABKQEKBCkCAlEtAAABKQEKBCkAAlUtAAABKwESBCkCAlUtAAABKwEiBCkAAlktAAABKgEWBCkCAlktAAABKQEKBCkAAl0tAAABKQEGBCkCAl0tAAABKwESBCkAAmEtAAABKQEKBCkCAmEtAAABKwEyBCkAAmUtAAABKQE2BCkAAmktAAABKwEiBCkAAm0tAAABKAESBCkCAm0tAAABKAESBCkAAnEtAAABKQEKBCkCAnEtAAABKwE6BCkAAnUtAAABKgEOBCkAAnggAAIAfAIAAPQAAAAQKAAAAVXNlckNoZWNrAAQQAAAAMTBUYWdlRHVyY2hmYWxsAAQEAAAARGF5AAQEAAAAMDUyAAQQAAAANCA4IGw1IEk2IDIzIDQyAAQEAAAAMDMwAAQNAAAAYmV0bGVuZWRkeWRkAAQEAAAAMDQ1AAQLAAAAYnJ1enluc2VubgAEBAAAADM2NgAEEAAAAGJyaWdodCBkYXlsaWdodAAEBAAAADAyNgAEEAAAAEJsdW1peGlmaWNhdGlvbgAECAAAAEIwQVQyNDEABAQAAAAwNDQABAoAAABjYWp2cHRreHgABAQAAAAwMzcABAkAAABDYW5lbG9SRAAECwAAAENvbXBicm9hcmsABAQAAAAwMjQABA8AAABDWUJFUkMwUk4wMjA3NwAEDQAAAGNlaXRoYXJsaW5kYQAEBAAAADA0NgAEDgAAAENhbGFtaXR5IDI4MTAABAQAAAAwODAABAkAAABkYW5pYWw4MQAEBwAAAGVsbHplcgAEBAAAADA1MAAEDQAAAGZlbGl6YWJyaWFseQAEEAAAAEdvdHQgWmVyc3TDtnJlcgAEBwAAAGdocmpvdgAEDQAAAM6XZWFydGJyb2tlbgAEBAAAADAyOQAECwAAAEhlbGxzaW5nMjQABAcAAABocm16c20ABAQAAAAwNTEABBEAAABKTSBOZXZlciBHaXZlIFVwAAQEAAAAMDI1AAQLAAAAS2Fib29tNDIwMQAEBAAAADAzNgAECwAAAGtyYXBvbnRpbmsABAkAAABMdXjDoG5uYQAECQAAAE1hZGE0OTEwAAQLAAAATc6RSU5TVM6RWQAECwAAAE1hcnRpbmFsVmcABAkAAABtZmtidmZpdgAEDgAAAE9tZWdhIFBvcnVuZ2EABAkAAABxZWtrNWlUVwAECgAAAFLEmXNjcmlwdAAEBwAAAFJoeW5haQAECwAAAFNhd2luY2xvbmcABAQAAAAwMzgABAoAAABUc21TdWNjbWEABAQAAAAwMjMABAYAAAB1WWFsZQAEEAAAAFdlR2V0dGluUGFpZEJieQAECQAAAFh0cmFTaDF0AAQGAAAAWW9uaWUABAkAAAB6dnR5dmlwZAAEBAAAADA3MQAECgAAAHp2cnVhZ2lsegAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAA=="),nil,"bt",_ENV))()
-- 0.43
