local b = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local function Base64Decode(data)
    data = string.gsub(data, '[^'..b..'=]', '')
    return (data:gsub('.', function(x)
        if (x == '=') then return '' end
        local r,f='',(b:find(x)-1)
        for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end
        return r;
    end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)
        if (#x ~= 8) then return '' end
        local c=0
        for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end
        return string.char(c)
    end))
end

assert(load(Base64Decode("G0x1YVIAAQQEBAgAGZMNChoKAAAAAAAAAAAAAQKNAAAACwAHAEtAAABKwECBCkCAgEtAAABKQEGBCkAAgktAAABKwEGBCkAAg0tAAABKQEKBCkAAhEtAAABKwEKBCkAAhUtAAABKwECBCkAAhktAAABKgEOBCkCAhktAAABKAESBCkCAh0tAAABKAESBCkCAiEtAAABKwESBCkAAiUtAAABKQEKBCkAAiktAAABKgEWBCkCAiktAAABKAEaBCkCAi0tAAABKQEGBCkCAjEtAAABKwEaBCkAAjUtAAABKQEKBCkAAjktAAABKQEKBCkCAjktAAABKAESBCkAAj0tAAABKAEiBCkCAj0tAAABKgEiBCkCAkEtAAABKwEGBCkCAkUtAAABKQEmBCkAAkktAAABKwEmBCkAAk0tAAABKQEqBCkAAlEtAAABKwEqBCkAAlUtAAABKQEKBCkAAlktAAABKgEuBCkCAlktAAABKwEmBCkCAl0tAAABKQEKBCkAAmEtAAABKQEKBCkCAmEtAAABKwESBCkAAmUtAAABKQEmBCkCAmUtAAABKgEWBCkAAmktAAABKAEiBCkCAmktAAABKQEKBCkAAm0tAAABKQEGBCkCAm0tAAABKwESBCkAAnEtAAABKQEKBCkCAnEtAAABKwE6BCkAAnUtAAABKQE+BCkAAnktAAABKQEmBCkAAn0tAAABKAESBCkCAn0tAAABKAESBCkAAoEtAAABKQEKBCkCAoEtAAABKwFCBCkAAoUtAAABKgEOBCkAAoggAAIAfAIAARQAAAAQKAAAAVXNlckNoZWNrAAQQAAAAMTBUYWdlRHVyY2hmYWxsAAQEAAAARGF5AAQEAAAAMDUyAAQQAAAANCA4IGw1IEk2IDIzIDQyAAQEAAAAMDMwAAQNAAAAYmV0bGVuZWRkeWRkAAQEAAAAMDQ1AAQLAAAAYnJ1enluc2VubgAEBAAAADM2NgAEEAAAAGJyaWdodCBkYXlsaWdodAAEBAAAADAyNgAEEAAAAEJsdW1peGlmaWNhdGlvbgAECAAAAEIwQVQyNDEABAQAAAAwNDQABAoAAABjYWp2cHRreHgABAQAAAAwMzcABAkAAABDYW5lbG9SRAAECwAAAENvbXBicm9hcmsABAQAAAAwMjQABA8AAABDWUJFUkMwUk4wMjA3NwAEDQAAAGNlaXRoYXJsaW5kYQAEBAAAADA0NgAEDgAAAENhbGFtaXR5IDI4MTAABAQAAAAwODAABAkAAABkYW5pYWw4MQAEBwAAAGVsbHplcgAEBAAAADA1MAAEDQAAAGZlbGl6YWJyaWFseQAEEAAAAEdvdHQgWmVyc3TDtnJlcgAEBwAAAGdocmpvdgAEBwAAAGdydXl4eAAEBAAAADA2MgAEDQAAAM6XZWFydGJyb2tlbgAEBAAAADAyOQAECwAAAEhlbGxzaW5nMjQABAcAAABocm16c20ABAQAAAAwNTEABAoAAABoYXBweWdvZ28ABAQAAAAwNjQABBEAAABKTSBOZXZlciBHaXZlIFVwAAQEAAAAMDI1AAQLAAAAS2Fib29tNDIwMQAEBAAAADAzNgAECwAAAGtyYXBvbnRpbmsABAkAAABrdWthY2FkYQAEBAAAADA1OAAEDgAAAEtlcmlzYWlzZW1vYW4ABAkAAABMdXjDoG5uYQAECQAAAE1hZGE0OTEwAAQLAAAATc6RSU5TVM6RWQAECwAAAE1hcnRpbmFsVmcABAkAAABtZmtidmZpdgAECAAAAE5pZGF5w4oABA4AAABPbWVnYSBQb3J1bmdhAAQJAAAAcWVrazVpVFcABAoAAABSxJlzY3JpcHQABAcAAABSaHluYWkABAsAAABTYXdpbmNsb25nAAQEAAAAMDM4AAQKAAAAVHNtU3VjY21hAAQEAAAAMDIzAAQGAAAAdVlhbGUABBAAAABXZUdldHRpblBhaWRCYnkABAkAAABYdHJhU2gxdAAEBgAAAFlvbmllAAQJAAAAenZ0eXZpcGQABAQAAAAwNzEABAoAAAB6dnJ1YWdpbHoAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAA="),nil,"bt",_ENV))()
-- 0.51
